spring:
  mail:
    host: smtp.163.com
    username: yaomengdi0429@163.com
    password: *
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: *
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
